# Generated by Django 5.2.3 on 2025-07-05 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='carrera',
            field=models.ForeignKey(default='Base de datos', on_delete=django.db.models.deletion.CASCADE, to='api.carrera'),
            preserve_default=False,
        ),
    ]
