# Generated by Django 5.2.3 on 2025-07-03 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='ano',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='semestre',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='api.curso'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='api.estudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('estudiante', 'curso', 'ano', 'semestre')},
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
